project:
  type: website

website:
  title: "Grammar of Data Manipulation"
  navbar:
    logo: logo.png
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
  sidebar:
    - id: manual
      contents:
        - text: 'Intro'
          href: index.qmd
        - text: "---"
        - section: 'Column Selection'
          contents:
          - text: '1 By name'
            href: manual/column-selection-name.qmd
          - text: '2 Exclusions'
            href: manual/column-selection-exclusion.qmd
          - text: '3 Data Types'
            href: manual/column-selection-types.qmd
          - text: '4 Name Patterns'
            href: manual/column-selection-patterns.qmd
format:
  html:
    toc: true
    theme: minty
    code-copy: true
    code-overflow: wrap
    css: styles.css

