project:
  type: website

website:
  title: "Grammar of Data Manipulation"
  navbar:
    logo: logo.png
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
  sidebar:
    - id: manual
      contents:
        - text: 'Intro'
          href: index.qmd
        - text: "---"
        - section: 'Get Started'
          contents:
          - text: 'Column Selection'
            href: manual/column-selection.qmd
format:
  html:
    toc: true
    theme: minty
    code-copy: true
    code-overflow: wrap
    css: styles.css

editor: visual

