---
title: "Summarize a dataframe with `skim` aka `describe`"
subtitle: "Get a quick understanding of your dataframe's basic properties"
format: 
  html:
    toc: true
    df-print: kable
    self-contained: true
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
---

```{r setup}
#| echo: false
library(reticulate)
library(janitor)
library(tidyverse)
library(skimr)
use_virtualenv("../../venv/")

df = tibble(
  color = c("blue","red","green"),
  size = c("small", "large", "large"),
  value_weight = c(3,8,9),
  value_height = c(12, 45, 42)
)
```

```{python}
#| echo: false
import polars as pl

df = pl.DataFrame(
    {
        "color": ["blue", "red", "green"],
        "size": ["small", "large", "large"],
        "value_weight": [3, 8, 9],
        "value_height": [12, 45, 42],
    }
)
```

::: columns
::: {.column width="49%"}
::: callout-note
## Tidyverse

```{r}
#| eval: false
df %>% skim()
```
:::
:::

::: {.column width="2%"}
:::

::: {.column width="49%"}
::: callout-tip
## Polars

```{python}
#| eval: false
df.describe()
```
:::
:::
:::

::: {.panel-tabset}
## R

``` {r}
#| echo: false
df %>% skim()
```

## Python

``` {python}
#| echo: false
df.describe()
```

:::

## API Links:

-   [skimr::skim()](https://docs.ropensci.org/skimr/reference/skim.html)
-   [polars.describe](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.describe.html#polars.DataFrame.describe)
